apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: service-account-key
spec:
  backendType: gcpSecretsManager
  projectId: ${SECRET_PROJECT}
  data:
    - key: ${KUBEFLOW_PROJECT}-cert-manager-service-account-key
      name: key.json
      property: key.json
      version: latest
