apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
spec:
  backendType: gcpSecretsManager
  projectId: ${SECRET_PROJECT}
  data:
    - key: ${KUBEFLOW_PROJECT}/kubeflow/cert-manager-secrets
      name: key.json
      property: key.json
      version: latest
