apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
spec:
  interval: 5m
  path: kustomize/manifests/cluster/overlays/compute/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: flux-system
