apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.kubeflow-sbsc.n9s.mx.'
spec:
  type: LoadBalancer
  loadBalancerIP: '34.136.190.62'
