apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.staging.n9s.mx.'
spec:
  type: LoadBalancer
  loadBalancerIP: '34.133.164.37'
