apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: compute-sach.neuralnetes.com.
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
