apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: service-account-key
spec:
  backendType: gcpSecretsManager
  projectId: secret-hcwb
  data:
    - key: kubeflow-hcwb-cert-manager-service-account-key
      name: key.json
      version: latest
