apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  annotations:
    iam.gke.io/gcp-service-account: cert-manager-meuf@iam-meuf.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: cert-manager-meuf@iam-meuf.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook
  annotations:
    iam.gke.io/gcp-service-account: cert-manager-meuf@iam-meuf.iam.gserviceaccount.com
