apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: "system:masters"
  kind: Group
  apiGroup: rbac.authorization.k8s.io
- name: "terraform@terraform-neuralnetes.iam.gserviceaccount.com"
  kind: User
  apiGroup: rbac.authorization.k8s.io
