resources:
- ../../namespaces/compute
- ../../flux-system/base
- ../../kubernetes-external-secrets/overlays/compute
- ../../external-dns/overlays/compute
- ../../nvidia-driver-installer/gcp
- ../../kubeflow/1.2/overlays/compute
