apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cainjector
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
roleRef:
  name: cert-manager-cainjector
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager-cainjector
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-issuers
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-issuers
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-clusterissuers
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-clusterissuers
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-certificates
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-certificates
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-orders
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-orders
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-challenges
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-challenges
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-ingress-shim
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-ingress-shim
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
