apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-cainjector
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
rules:
- resources:
  - certificates
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - update
  - patch
- resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  apiGroups:
  - admissionregistration.k8s.io
  verbs:
  - get
  - list
  - watch
  - update
- resources:
  - apiservices
  apiGroups:
  - apiregistration.k8s.io
  verbs:
  - get
  - list
  - watch
  - update
- resources:
  - customresourcedefinitions
  apiGroups:
  - apiextensions.k8s.io
  verbs:
  - get
  - list
  - watch
  - update
- resources:
  - auditsinks
  apiGroups:
  - auditregistration.k8s.io
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-issuers
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - issuers
  - issuers/status
  apiGroups:
  - cert-manager.io
  verbs:
  - update
- resources:
  - issuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-clusterissuers
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - clusterissuers
  - clusterissuers/status
  apiGroups:
  - cert-manager.io
  verbs:
  - update
- resources:
  - clusterissuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-certificates
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - certificates
  - certificates/status
  - certificaterequests
  - certificaterequests/status
  apiGroups:
  - cert-manager.io
  verbs:
  - update
- resources:
  - certificates
  - certificaterequests
  - clusterissuers
  - issuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - certificates/finalizers
  - certificaterequests/finalizers
  apiGroups:
  - cert-manager.io
  verbs:
  - update
- resources:
  - orders
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-orders
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - orders
  - orders/status
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - update
- resources:
  - orders
  - challenges
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - clusterissuers
  - issuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - challenges
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - create
  - delete
- resources:
  - orders/finalizers
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - update
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-challenges
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - challenges
  - challenges/status
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - update
- resources:
  - challenges
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - issuers
  - clusterissuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
- resources:
  - pods
  - services
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- resources:
  - ingresses
  apiGroups:
  - networking.k8s.io
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- resources:
  - routes/custom-host
  apiGroups:
  - route.openshift.io
  verbs:
  - create
- resources:
  - challenges/finalizers
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - update
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-ingress-shim
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
- resources:
  - certificates
  - certificaterequests
  apiGroups:
  - cert-manager.io
  verbs:
  - create
  - update
  - delete
- resources:
  - certificates
  - certificaterequests
  - issuers
  - clusterissuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - ingresses
  apiGroups:
  - networking.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - ingresses/finalizers
  apiGroups:
  - networking.k8s.io
  verbs:
  - update
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-view
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- resources:
  - certificates
  - certificaterequests
  - issuers
  apiGroups:
  - cert-manager.io
  verbs:
  - get
  - list
  - watch
- resources:
  - challenges
  - orders
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-edit
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- resources:
  - certificates
  - certificaterequests
  - issuers
  apiGroups:
  - cert-manager.io
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- resources:
  - challenges
  - orders
  apiGroups:
  - acme.cert-manager.io
  verbs:
  - get
  - list
  - watch
