crds:
- crds.yaml
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- role.yaml
- role-binding.yaml
- service-account.yaml
- service.yaml
- validating-webhook-configuration.yaml
- mutating-webhook-configuration.yaml
- deployment.yaml
