apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook:dynamic-serving
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
rules:
- resources:
  - secrets
  apiGroups:
  - ""
  resourceNames:
  - cert-manager-webhook-ca
  verbs:
  - get
  - list
  - watch
  - update
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
