apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook:dynamic-serving
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
roleRef:
  name: cert-manager-webhook:dynamic-serving
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager-webhook
  namespace: cert-manager
  kind: ServiceAccount
  apiGroup: ""
