apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: cloud-sdk
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
