apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-controller
rules:
- resources:
  - '*'
  apiGroups:
  - source.toolkit.fluxcd.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - kustomize.toolkit.fluxcd.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - helm.toolkit.fluxcd.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - notification.toolkit.fluxcd.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - image.toolkit.fluxcd.io
  verbs:
  - '*'
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
- resources:
  - configmaps
  - configmaps/status
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- resources:
  - leases
  apiGroups:
  - coordination.k8s.io
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reconciler
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: kustomize-controller
  namespace: flux-system
  kind: ServiceAccount
- name: helm-controller
  namespace: flux-system
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller
roleRef:
  name: crd-controller
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: kustomize-controller
  namespace: flux-system
  kind: ServiceAccount
- name: helm-controller
  namespace: flux-system
  kind: ServiceAccount
- name: source-controller
  namespace: flux-system
  kind: ServiceAccount
- name: notification-controller
  namespace: flux-system
  kind: ServiceAccount
- name: image-reflector-controller
  namespace: flux-system
  kind: ServiceAccount
- name: image-automation-controller
  namespace: flux-system
  kind: ServiceAccount
