apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.kubeflow-fehd.network-fehd.neuralnetes.com.'
spec:
  type: LoadBalancer
