apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monorepo
spec:
  dependsOn:
  - name: flux-system-namespace
  interval: 5m
  path: kustomize/manifests/flux-git-repository/monorepo
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: flux-system
