apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-1-3-1-stack
spec:
  dependsOn:
    - name: namespaces
  path: kustomize/manifests/kubeflow/1.2/overlays/compute/stacks/kubernetes/applications/istio-1-3-1-stack
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: istio-system