apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.cluster-akbq.network-akbq.com.'
spec:
  type: LoadBalancer

