---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-stack
spec:
  path: kustomize/manifests/kubeflow/1.2/overlays/compute/stacks/kubernetes/applications/istio-1-3-1-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  path: kustomize/manifests/kubeflow/1.2/overlays/compute/stacks/kubernetes/applications/cert-manager
