apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  dependsOn:
    - name: cert-manager-namespace
  path: kustomize/manifests/kubeflow/1.2/overlays/compute/stacks/kubernetes/applications/cert-manager
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: flux-system