# Source: kubernetes-external-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: external-secrets
        app.kubernetes.io/name: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
      - name: kubernetes-external-secrets
        image: "ghcr.io/external-secrets/kubernetes-external-secrets:6.4.0"
        ports:
        - name: prometheus
          containerPort: 3001
        env:
        - name: "LOG_LEVEL"
          value: "info"
        - name: "LOG_MESSAGE_KEY"
          value: "msg"
        - name: "METRICS_PORT"
          value: "3001"
        - name: "POLLER_INTERVAL_MILLISECONDS"
          value: "10000"
        - name: "VAULT_ADDR"
          value: "http://127.0.0.1:8200"
        - name: "WATCH_TIMEOUT"
          value: "60000"
          # Params for env vars populated from k8s secrets
        resources: {}
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
