# Source: kubernetes-external-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-secrets
spec:
  selector:
    app.kubernetes.io/name: external-secrets
  ports:
  - name: prometheus
    protocol: TCP
    port: 3001
    targetPort: prometheus
