apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
spec:
  dependsOn:
    - name: external-dns-namespace
  path: kustomize/manifests/external-dns/overlays/compute
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: external-dns