apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
spec:
  interval: 1m
  path: kustomize/manifests/istio-system/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: istio-system
