apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: bot+letsencrypt-prod@neuralnetes.com
    http01: null
    privateKeySecretRef: null
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          clouddns:
            project: network-xowz
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: bot+letsencrypt-staging@neuralnetes.com
    http01: null
    privateKeySecretRef: null
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          clouddns:
            project: network-xowz
---
