apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-namespace
spec:
  path: apps/namespace/external-dns/base
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests