apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-istiocontrolplane
spec:
  profile: default
meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
components:
  ingressGateways:
  - name: istio-ingressgateway
    enabled: true
    k8s:
      serviceAnnotations:
        external-dns.alpha.kubernetes.io/hostname: '*.n9s.mx.'
      service:
        type: LoadBalancer
        loadBalancerIP: '34.66.149.6'
  egressGateways:
  - name: istio-egressgateway
    enabled: true
