apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-staging
spec:
  dnsNames:
  - 'non-prod.n9s.mx'
  - '*.non-prod.n9s.mx'
#  - 'non-prod.neuralnetes.com'
#  - '*.neuralnetes.com'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-prod
spec:
  dnsNames:
  - 'non-prod.n9s.mx'
  - '*.non-prod.n9s.mx'
#  - 'non-prod.neuralnetes.com'
#  - '*.neuralnetes.com'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-certs-self-signed
spec:
  dnsNames:
  - 'non-prod.n9s.mx'
  - '*.non-prod.n9s.mx'
#  - 'non-prod.neuralnetes.com'
#  - '*.neuralnetes.com'
