namespace: flux-system
resources:
- ../../base
- ../../../external-secrets/overlays/kubeflow-cwtq
- ../../../external-dns/overlays/kubeflow-cwtq
- ../../../secrets/auth/overlays/kubeflow-cwtq
- ../../../secrets/cert-manager/overlays/kubeflow-cwtq
- ../../../secrets/kubeflow/overlays/kubeflow-cwtq
- ../../../secrets/istio-system/overlays/kubeflow-cwtq
- ../../../kubeflow/overlays/kubeflow-cwtq
- ../../../profiles/overlays/kubeflow-cwtq
patchesStrategicMerge:
- patch-flux-kustomization.yaml
