apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-namespace
spec:
  path: apps/namespace/flux-system/base
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo