apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs
spec:
  secretName: istio-certs
  dnsNames:
  - '*.network-abcd.neuralnetes.com'
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
