apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: istio-certs
spec:
  backendType: gcpSecretsManager
  projectId: secret-abcd
  data:
    - key: kubeflow.compute-abcd.network-abcd.neuralnetes.com
      name: cert
