apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'kubeflow.compute-ctut.network-ctut.neuralnetes.com.'
spec:
  type: LoadBalancer
