apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-secrets
spec:
  interval: 5m
  path: kustomize/manifests/secrets/kubeflow/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
