apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-namespace
spec:
  path: kustomize/manifests/namespace/kubeflow
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo