apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-namespace
spec:
  interval: 5m
  path: kustomize/manifests/namespace/kubeflow
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
