apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.n9s.mx.'
spec:
  type: LoadBalancer
  loadBalancerIP: '35.238.216.152'
