apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubernetes-external-secrets
spec:
  dependsOn:
    - name: kubernetes-external-secrets-namespace
  path: kubernetes-external-secrets/overlays/compute
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  targetNamespace: kubernetes-external-secrets