apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  labels:
    app: kind
spec:
  containers:
  - name: foo
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  type: NodePort
  selector:
    app: kind
  ports:
  - name: http
    port: 5678
    nodePort: 30950
