apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-staging
spec:
  renewBefore: 1440h
  dnsNames:
  - '*.n9s.mx'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-prod
spec:
  renewBefore: 1440h
  dnsNames:
  - '*.n9s.mx'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-self-signed
spec:
  renewBefore: 1440h
  dnsNames:
  - '*.n9s.mx'
