apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs
spec:
  dnsNames:
  - '*.non-prod.neuralnetes.com'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-prod
spec:
  dnsNames:
  - '*.non-prod.neuralnetes.com'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-self-signed
spec:
  dnsNames:
  - '*.non-prod.neuralnetes.com'
