apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- resources: ['endpoints', 'pods', 'services']
  apiGroups: ['']
  verbs: ['get', 'watch', 'list']
- resources: ['ingresses']
  apiGroups: ['extensions']
  verbs: ['get', 'watch', 'list']
- resources: ['nodes']
  apiGroups: ['']
  verbs: ['list']
