apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  name: external-dns
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: external-dns
  namespace: default
  kind: ServiceAccount
