images:
- name: k8s.gcr.io/external-dns/external-dns
  newTag: v0.7.5
resources:
- external-dns-deployment.yaml
- external-dns-serviceaccount.yaml
- external-dns-clusterrole.yaml
- external-dns-clusterrolebinding.yaml
