apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
spec:
  interval: 1m
  path: kustomize/manifests/flux-system/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: flux-system
