apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-local-gateway-1-3-1
spec:
  dependsOn:
    - name: namespaces
  path: kustomize/manifests/kubeflow/1.2/overlays/compute/stacks/kubernetes/applications/cluster-local-gateway-1-3-1
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: istio-system