apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-staging
spec:
  dnsNames:
  - '*.staging.n9s.mx'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-letsencrypt-prod
spec:
  dnsNames:
  - '*.staging.n9s.mx'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-certs-self-signed
spec:
  dnsNames:
  - '*.staging.n9s.mx'
