apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-namespaces
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/namespaces/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: application
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/application/v3
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-stack
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/istio-1-3-1-stack
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-local-gateway
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/cluster-local-gateway-1-3-1
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/istio/istio/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-crds
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/cert-manager-crds
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-kube-system-resources
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/cert-manager-kube-system-resources
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/cert-manager
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metacontroller
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/metacontroller/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oidc-authservice
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/oidc-authservice
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dex-auth
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes/application/dex-auth
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bootstrap
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/admission-webhook/bootstrap/overlays/application
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spark-operator
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/spark/spark-operator/overlays/application
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-apps
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/stacks/kubernetes
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/knative/installs/generic
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: knative-serving
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kfserving
spec:
  interval: 1m
  path: kustomize/manifests/kubeflow/1.2/base/kfserving/installs/generic
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: kubeflow
