apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  dependsOn:
    - name: cert-manager-namespace
  path: cert-manager/base
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: external-dns