apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: compute
spec:
  interval: 5m
  path: kustomize/manifests/flux-kustomization/cluster/overlays/compute
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: flux-system
