apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-profiles
spec:
  interval: 1m
  path: kustomize/manifests/profiles/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: profiles
