apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: bot+letencrypt-staging@neuralnetes.com
    solvers:
      - dns01:
          clouddns:
            project: dns-sbsc
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: bot+letencrypt-prod@neuralnetes.com
    solvers:
      - dns01:
          clouddns:
            project: dns-sbsc
