apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-namespace
spec:
  interval: 5m
  path: kustomize/manifests/namespace/cert-manager
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
