apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    spec:
      containers:
      - image: quay.io/dexidp/dex:v2.22.0
        name: dex
        command: ["dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: http
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: dex-secrets
          mountPath: /etc/dex/dex-secrets
        envFrom:
          - secretRef:
              name: dex-oidc-client
          - secretRef:
              name: dex-secrets
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: dex-secrets
        secret:
          secretName: dex-secrets
