apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
spec:
  interval: 1m
  path: kustomize/manifests/external-dns/base
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
  targetNamespace: external-dns
