apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
spec:
  interval: 5m
  path: kustomize/manifests/flux-kustomization/namespaces/compute
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
