apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
spec:
  path: kustomize/manifests/flux-kustomization/namespaces/compute/base
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
