apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system-namespace
spec:
  interval: 5m
  path: kustomize/manifests/namespace/istio-system
  prune: true
  sourceRef:
    name: monorepo
    kind: GitRepository
