apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: service-account-key
spec:
  backendType: gcpSecretsManager
  projectId: ${SECRET_PROJECT}
  data:
    - key: ${KUBEFLOW_PROJECT}-auth-service-account-key
      name: key.json
      property: key.json
      version: latest
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
spec:
  backendType: gcpSecretsManager
  projectId: ${SECRET_PROJECT}
  data:
    - key: ${KUBEFLOW_PROJECT}-auth-dex-secrets
      name: GOOGLE_CLIENT_ID
      property: GOOGLE_CLIENT_ID
      version: latest
    - key: ${KUBEFLOW_PROJECT}-auth-dex-secrets
      name: GOOGLE_CLIENT_SECRET
      property: GOOGLE_CLIENT_SECRET
      version: latest
