on:
  push:
    branches:
      - main
    paths:
      - 'terragrunt/**'
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TERRAGRUNT_COMMAND: run-all apply
    steps:
      - id: checkout
        name: run checkout
        uses: actions/checkout@v2
      - id: terragrunt_run_all_apply
        name: run workflow dispatch terragrunt run-all apply
        working-directory: ./bash/github-actions
        run: |
          export TERRAGRUNT_COMMAND='run-all apply'
          export TERRAGRUNT_WORKING_DIR="terragrunt/live/gcs"
          TERRAGRUNT_CLI_FLAGS="$(
            jq -nrc '[
              "--terragrunt-include-dir non-prod/global/terraform/**/**",
              "--terragrunt-include-dir non-prod/global/iam/**/**",
              "--terragrunt-include-dir non-prod/global/secret/**/**",
              "--terragrunt-include-dir non-prod/global/network/**/**",
              "--terragrunt-include-dir non-prod/global/data/**/**",
              "--terragrunt-include-dir non-prod/global/compute/**/**",
              "--terragrunt-include-dir non-prod/us-central1/network/**/**",
              "--terragrunt-include-dir non-prod/us-central1/data/**/**",
              "--terragrunt-include-dir non-prod/us-central1/compute/**/**"
            ]'
          )"
          export TERRAGRUNT_CLI_FLAGS
          chmod +x ./workflow_dispatch_terragrunt.sh && ./workflow_dispatch_terragrunt.sh
