on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'terragrunt/**'
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TERRAGRUNT_COMMAND: run-all apply
    steps:
      - id: checkout
        name: run checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - id: terragrunt_run_all_apply
        name: run workflow dispatch terragrunt run-all apply
        run: |
          source "${GITHUB_WORKSPACE}/bash/terraform/functions.sh"
          source "${GITHUB_WORKSPACE}/bash/terragrunt/functions.sh"
          source "${GITHUB_WORKSPACE}/bash/github/functions.sh"
          post_github_workflow_dispatch_terragrunt_non_prod
