on:
  workflow_dispatch:
    inputs:
      iam:
        description: 'iam'
        required: true
      secret:
        description: 'secret'
        required: true
      network:
        description: 'network'
        required: true
      data:
        description: 'data'
        required: true
      compute:
        description: 'compute'
        required: true
      shared:
        description: 'shared'
        required: true
      terragrunt_working_dir:
        description: 'terragrunt_working_dir'
        required: true
      terragrunt_run_all_command:
        description: 'terragrunt_run_all_command'
        required: true
env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_PROVIDER_KUSTOMIZATION_VERSION: 0.4.2
  GCP_BILLING_ACCOUNT: ${{ secrets.GCP_BILLING_ACCOUNT }}
  GCP_GSUITE_DOMAIN_NAME: ${{ secrets.GCP_GSUITE_DOMAIN_NAME }}
  GCP_ORG: ${{ secrets.GCP_ORG }}
  GCP_ORG_ID: ${{ secrets.GCP_ORG_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCS_TERRAFORM_REMOTE_STATE_BUCKET: ${{ secrets.GCS_TERRAFORM_REMOTE_STATE_BUCKET }}
  GCS_TERRAFORM_REMOTE_STATE_LOCATION: ${{ secrets.GCS_TERRAFORM_REMOTE_STATE_LOCATION }}
jobs:
  terragrunt_run_all:
    runs-on: ubuntu-latest
    steps:
    - name: run checkout
      uses: actions/checkout@v2
    - name: run setup GITHUB_ENV
      working-directory: ./hack/github-actions
      run: |
        IAM=${{ github.event.inputs.iam }}
        SECRET=${{ github.event.inputs.secret }}
        NETWORK=${{ github.event.inputs.network }}
        DATA=${{ github.event.inputs.data }}
        COMPUTE=${{ github.event.inputs.compute }}
        SHARED=${{ github.event.inputs.shared }}
        TERRAGRUNT_WORKING_DIR=${{ github.event.inputs.terragrunt_working_dir }}
        TERRAGRUNT_RUN_ALL_COMMAND=${{ github.event.inputs.terragrunt_run_all_command }}
        HOME_BIN="${HOME}/bin"
        mkdir -p "${HOME_BIN}"
        source github_env.sh
        source terragrunt_env.sh
    - name: run setup GITHUB_PATH
      working-directory: ./hack/github-actions
      run: source github_path.sh
    - name: run setup tfenv
      working-directory: ./hack/github-actions
      run: source setup_tfenv.sh
    - name: run setup tgenv
      working-directory: ./hack/github-actions
      run: source setup_tgenv.sh
    - name: run setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true
    - name: run ssh-agent
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run terragrunt run-all network
      if: env.NETWORK == 'true'
      run: |
        terragrunt run-all "${TERRAGRUNT_RUN_ALL_COMMAND}" \
          --terragrunt-include-dir "global/network/**/**" \
          --terragrunt-include-dir "us-central1/network/**/**"
    - name: run terragrunt run-all secret
      if: env.SECRET == 'true'
      run: |
        terragrunt run-all "${TERRAGRUNT_RUN_ALL_COMMAND}" \
          --terragrunt-include-dir "global/secret/**/**"
    - name: run terragrunt run-all iam
      if: env.IAM == 'true'
      run: |
        terragrunt run-all "${TERRAGRUNT_RUN_ALL_COMMAND}" \
          --terragrunt-include-dir "global/iam/**/**"
    - name: run terragrunt run-all data
      if: env.DATA == 'true'
      run: |
        terragrunt run-all "${TERRAGRUNT_RUN_ALL_COMMAND}" \
          --terragrunt-include-dir "global/data/**/**" \
          --terragrunt-include-dir "us-central1/data/**/**"
    - name: run terragrunt run-all compute
      if: env.COMPUTE == 'true'
      run: |
        terragrunt run-all "${TERRAGRUNT_RUN_ALL_COMMAND}" \
          --terragrunt-include-dir "global/compute/**/**" \
          --terragrunt-include-dir "us-central1/compute/**/**"
