on:
  workflow_dispatch:
    inputs:
      iam:
        description: 'iam'
        required: true
      secret:
        description: 'secret'
        required: true
      network:
        description: 'network'
        required: true
      data:
        description: 'data'
        required: true
      compute:
        description: 'compute'
        required: true
      shared:
        description: 'shared'
        required: true
      terragrunt_working_dir:
        description: 'terragrunt_working_dir'
        required: true
      terragrunt_command:
        description: 'terragrunt_command'
        required: true
defaults:
  run:
    shell: bash
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: run checkout
      uses: actions/checkout@v2
    - id: setup_github_env
      name: run setup github env
      run: |
        COMPUTE=${{ github.event.inputs.compute }}
        DATA=${{ github.event.inputs.data }}
        GCP_BILLING_ACCOUNT_ID=${{ secrets.GCP_BILLING_ACCOUNT_ID }}
        GCP_ORGANIZATION=${{ secrets.GCP_ORGANIZATION }}
        GCP_ORGANIZATION_ID=${{ secrets.GCP_ORGANIZATION_ID }}
        GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_KEY=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        IAM=${{ github.event.inputs.iam }}
        NETWORK=${{ github.event.inputs.network }}
        SECRET=${{ github.event.inputs.secret }}
        SHARED=${{ github.event.inputs.shared }}
        TERRAGRUNT_COMMAND=${{ github.event.inputs.terragrunt_command }}
        TERRAGRUNT_WORKING_DIR=${{ github.event.inputs.terragrunt_working_dir }}
        TF_INPUT="false"
        TF_IN_AUTOMATION="true"
        TF_PROVIDER_GITHUB_VERSION="4.5.1"
        TF_PROVIDER_GOOGLE_BETA_VERSION="3.59.0"
        TF_PROVIDER_GOOGLE_VERSION="3.59.0"
        TF_PROVIDER_KUSTOMIZATION_VERSION="0.4.2"
        TF_PROVIDER_RANDOM_VERSION="3.1.0"
        HOME_BIN="${HOME}/bin"
        echo "COMPUTE=$COMPUTE" >> "${GITHUB_ENV}"
        echo "DATA=$DATA" >> "${GITHUB_ENV}"
        echo "GCP_BILLING_ACCOUNT_ID=$GCP_BILLING_ACCOUNT_ID" >> "${GITHUB_ENV}"
        echo "GCP_ORGANIZATION=$GCP_ORGANIZATION" >> "${GITHUB_ENV}"
        echo "GCP_ORGANIZATION_ID=$GCP_ORGANIZATION_ID" >> "${GITHUB_ENV}"
        echo "GCP_WORKSPACE_DOMAIN_NAME=$GCP_WORKSPACE_DOMAIN_NAME" >> "${GITHUB_ENV}"
        echo "GITHUB_ORGANIZATION=$GITHUB_ORGANIZATION" >> "${GITHUB_ENV}"
        echo "GITHUB_REF=$GITHUB_REF" >> "${GITHUB_ENV}"
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> "${GITHUB_ENV}"
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> "${GITHUB_ENV}"
        echo "GITHUB_USER=$GITHUB_USER" >> "${GITHUB_ENV}"
        echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> "${GITHUB_ENV}"
        echo "HOME_BIN=$HOME_BIN" >> "${GITHUB_ENV}"
        echo "IAM=$IAM" >> "${GITHUB_ENV}"
        echo "NETWORK=$NETWORK" >> "${GITHUB_ENV}"
        echo "SECRET=$SECRET" >> "${GITHUB_ENV}"
        echo "SHARED=$SHARED" >> "${GITHUB_ENV}"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> "${GITHUB_ENV}"
        echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY" >> "${GITHUB_ENV}"
        echo "TERRAFORM_CLOUD_ORGANIZATION=$TERRAFORM_CLOUD_ORGANIZATION" >> "${GITHUB_ENV}"
        echo "TERRAFORM_CLOUD_TOKEN=$TERRAFORM_CLOUD_TOKEN" >> "${GITHUB_ENV}"
        echo "TERRAGRUNT_COMMAND=$TERRAGRUNT_COMMAND" >> "${GITHUB_ENV}"
        echo "TERRAGRUNT_WORKING_DIR=$TERRAGRUNT_WORKING_DIR" >> "${GITHUB_ENV}"
        echo "TF_INPUT=$TF_INPUT" >> "${GITHUB_ENV}"
        echo "TF_IN_AUTOMATION=$TF_IN_AUTOMATION" >> "${GITHUB_ENV}"
        echo "TF_PROVIDER_GITHUB_VERSION=$TF_PROVIDER_GITHUB_VERSION" >> "${GITHUB_ENV}"
        echo "TF_PROVIDER_GOOGLE_BETA_VERSION=$TF_PROVIDER_GOOGLE_BETA_VERSION" >> "${GITHUB_ENV}"
        echo "TF_PROVIDER_GOOGLE_VERSION=$TF_PROVIDER_GOOGLE_VERSION" >> "${GITHUB_ENV}"
        echo "TF_PROVIDER_KUSTOMIZATION_VERSION=$TF_PROVIDER_KUSTOMIZATION_VERSION" >> "${GITHUB_ENV}"
        echo "TF_PROVIDER_RANDOM_VERSION=$TF_PROVIDER_RANDOM_VERSION" >> "${GITHUB_ENV}"
    - id: setup_github_path
      name: run setup github path
      run: |
        mkdir -p "${HOME_BIN}"
        echo "${HOME_BIN}" >> "${GITHUB_PATH}"
    - id: setup_gcloud
      name: run setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - id: setup_tfenv
      name: run setup tfenv
      working-directory: ./bash/terraform
      run: |
        chmod +x ./setup_tfenv.sh
        ./setup_tfenv.sh
    - id: setup_tgenv
      name: run setup tgenv
      working-directory: ./bash/terragrunt
      run: |
        chmod +x ./setup_tgenv.sh
        ./setup_tgenv.sh
    - id: setup_ssh_agent
      name: run setup ssh agent
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - id: terragrunt_command_iam
      if: env.IAM == 'true'
      name: run terragrunt command iam
      run: |
        terragrunt "${TERRAGRUNT_COMMAND}" \
          --terragrunt-include-dir "global/iam/**/**"
    - id: terragrunt_command_secret
      if: env.SECRET == 'true'
      name: run terragrunt command secret
      run: |
        terragrunt "${TERRAGRUNT_COMMAND}" \
          --terragrunt-include-dir "global/secret/**/**"
    - id: terragrunt_command_network
      if: env.NETWORK == 'true'
      name: run terragrunt command network
      run: |
        terragrunt "${TERRAGRUNT_COMMAND}" \
          --terragrunt-include-dir "global/network/**/**" \
          --terragrunt-include-dir "us-central1/network/**/**"
    - id: terragrunt_command_data
      if: env.DATA == 'true'
      name: run terragrunt command data
      run: |
        terragrunt "${TERRAGRUNT_COMMAND}" \
          --terragrunt-include-dir "global/data/**/**" \
          --terragrunt-include-dir "us-central1/data/**/**"
    - id: terragrunt_command_compute
      if: env.COMPUTE == 'true'
      name: run terragrunt command compute
      run: |
        terragrunt "${TERRAGRUNT_COMMAND}" \
          --terragrunt-include-dir "global/compute/**/**" \
          --terragrunt-include-dir "us-central1/compute/**/**"
