on:
  workflow_dispatch: {}
jobs:
  gcloud_projects_delete:
    runs-on: ubuntu-latest
    steps:
    - id: run_checkout
      name: run checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - id: run_setup_gcloud
      name: run setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - id: run_gcloud_components_install
      name: run gcloud components install
      run: gcloud components install alpha -q
    - id: run_gcloud_projects_delete
      name: run gcloud projects delete
      env:
        GCS_TERRAFORM_REMOTE_STATE_BUCKET: ${{ secrets.GCS_TERRAFORM_REMOTE_STATE_BUCKET }}
      run: |
        source "${GITHUB_WORKSPACE}/bash/google/functions.sh"
        source "${GITHUB_WORKSPACE}/bash/workspace/base/.envrc-google"
        projects_delete
