on:
  workflow_dispatch:
    inputs:
      terragrunt_cli_flags:
        description: terragrunt_cli_flags
        required: true
      terragrunt_command:
        description: terragrunt_command
        required: true
      terragrunt_working_dir:
        description: terragrunt_working_dir
        required: true
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: run checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - id: setup_github_user
      env:
        GITHUB_USER: ${{ secrets.GH_USER }}
        GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
      run: |
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_USER}"
    - id: setup_github_path
      name: run setup github path
      run: mkdir -p "${HOME}/.local/bin" && echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - id: setup_tfenv
      name: run setup tfenv
      working-directory: ./bash/terraform
      run: chmod +x ./setup_tfenv.sh && ./setup_tfenv.sh
    - id: setup_tgenv
      name: run setup tgenv
      working-directory: ./bash/terragrunt
      run: chmod +x ./setup_tgenv.sh && ./setup_tgenv.sh
    - id: setup_gcloud
      name: run setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - id: terragrunt_command
      name: run terragrunt command
      env:
        GCP_BILLING_ACCOUNT_ID: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
        GCP_ORGANIZATION: ${{ secrets.GCP_ORGANIZATION }}
        GCP_ORGANIZATION_ID: ${{ secrets.GCP_ORGANIZATION_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_WORKSPACE_DOMAIN_NAME: ${{ secrets.GCP_WORKSPACE_DOMAIN_NAME }}
        GCS_TERRAFORM_REMOTE_STATE_BUCKET: ${{ secrets.GCS_TERRAFORM_REMOTE_STATE_BUCKET }}
        GCS_TERRAFORM_REMOTE_STATE_LOCATION: ${{ secrets.GCS_TERRAFORM_REMOTE_STATE_LOCATION }}
        GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
        GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_USER: ${{ secrets.GH_USER }}
        GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
        GRAFANA_AUTH: ${{ secrets.GRAFANA_AUTH }}
        GRAFANA_ORG_ID: ${{ secrets.GRAFANA_ORG_ID }}
        GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
        TERRAGRUNT_CLI_FLAGS: ${{ toJSON(fromJSON(github.event.inputs.terragrunt_cli_flags)) }}
        TERRAGRUNT_COMMAND: ${{ github.event.inputs.terragrunt_command }}
        TERRAGRUNT_WORKING_DIR: ${{ github.workspace }}/${{ github.event.inputs.terragrunt_working_dir }}
        TF_INPUT: false
      run: |
        terragrunt_cli_flags=($(echo "${TERRAGRUNT_CLI_FLAGS}" | jq -rc '@sh' | tr -d \'\"))
        command=(
          terragrunt
          ${TERRAGRUNT_COMMAND}
          ${terragrunt_cli_flags[@]}
        )
        echo "command: ${command[@]}"
        "${command[@]}"
