apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: bot+letencrypt-staging@neuralnetes.com
    solvers:
      - dns01:
          clouddns:
            project: network-fehd
            serviceAccountSecretRef:
              name: service-account-key
              key: key.json
